// Vercel serverless entry point.
//
// On Replit the app runs as a single long-lived Express server (see
// server/index.ts). Vercel instead runs serverless functions, so this file
// wraps the same Express routes as an on-demand handler. Every request to
// /api/* is routed here and handled by Express exactly as it is in dev.
//
// ./_app.cjs is generated by the Vercel buildCommand (see vercel.json): it is
// an esbuild bundle of server/app.ts with all local source inlined into one
// file, which avoids Node ESM's "cannot find module" errors that occur when
// the function's relative imports are emitted without file extensions.
// @ts-expect-error generated at build time, no types available
import appModule from "./_app.cjs";
import type { Express, Request, Response } from "express";

const createApp = (appModule as { createApp: () => Promise<Express> }).createApp;

let appPromise: Promise<Express> | null = null;

export default async function handler(req: Request, res: Response) {
  try {
    if (!appPromise) {
      appPromise = createApp();
    }
    const app = await appPromise;
    return (app as unknown as (req: unknown, res: unknown) => void)(req, res);
  } catch (err) {
    // Reset so a transient failure can retry on the next invocation.
    appPromise = null;
    const message = err instanceof Error ? err.message : String(err);
    res.statusCode = 500;
    res.setHeader("content-type", "application/json");
    res.end(JSON.stringify({ error: "api_init_failed", message }));
  }
}
